version: '3.1'
services:
  db:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
      POSTGRES_DB: platziMarket
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    user: '999:999'
  adminer:
    image: adminer
    restart: always
    ports:
      - 55433:8080